import {
  HydrationBoundary,
  dehydrate,
  QueryClient,
} from "@tanstack/react-query";
import { THEME_LIST } from "amvasdev-ui";
import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import "amvasdev-ui/dist/index.css";
import "./globals.css";
import { Sidebar, Navbar } from "@/components";
import { THEME_COOKIE } from "@/constants/cookies";
import Provider from "@/provider";
import {
  COMPONENTS_QUERY_KEY,
  getAllComponents,
} from "@/queries/useComponents";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStorage = cookies();
  const theme = cookieStorage.get(THEME_COOKIE)?.value ?? THEME_LIST[0];
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryKey: COMPONENTS_QUERY_KEY,
    queryFn: getAllComponents,
  });

  return (
    <html lang="en" data-theme={theme}>
      <body className={clsx("bg-base-200", inter.className)}>
        <Provider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <div className="w-full min-h-svh flex">
              <Sidebar />
              <div className="flex xl:ml-80 flex-col w-full h-fit max-h-svh overflow-y-auto min-h-[calc(100svh-4.5rem)]">
                <Navbar />
                <div className="px-4 py-3 mx-auto max-w-[1540px] w-full">
                  {children}
                </div>
              </div>
            </div>
          </HydrationBoundary>
        </Provider>
      </body>
    </html>
  );
}
