import { THEME_LIST } from "amvasdev-ui";
import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import "amvasdev-ui/dist/index.css";
import "./globals.css";
import { Sidebar, Navbar } from "@/components";
import { THEME_COOKIE } from "@/constants/cookies";
import Provider from "@/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStorage = cookies();
  const theme = cookieStorage.get(THEME_COOKIE)?.value ?? THEME_LIST[0];

  return (
    <html lang="en" data-theme={theme}>
      <body className={clsx("bg-base-200", inter.className)}>
        <Provider>
          <div className="w-full min-h-svh flex">
            <Sidebar />
            <div className="flex lg:ml-80 flex-col w-full h-fit max-h-svh overflow-y-auto min-h-[calc(100svh-4.5rem)]">
              <Navbar />
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
